from flask import Flask, request, render_template, redirect, url_for, session, abort
import os

# _____ ______    _________        _________   ________   ___  __     _______    ________           ___       __    _______    ________   ________   ___   _________   _______      
#|\   _ \  _   \ |\___   ___\     |\___   ___\|\   __  \ |\  \|\  \  |\  ___ \  |\   ___  \        |\  \     |\  \ |\  ___ \  |\   __  \ |\   ____\ |\  \ |\___   ___\|\  ___ \     
#\ \  \\\__\ \  \\|___ \  \_|     \|___ \  \_|\ \  \|\  \\ \  \/  /|_\ \   __/| \ \  \\ \  \       \ \  \    \ \  \\ \   __/| \ \  \|\ /_\ \  \___|_\ \  \\|___ \  \_|\ \   __/|    
# \ \  \\|__| \  \    \ \  \           \ \  \  \ \  \\\  \\ \   ___  \\ \  \_|/__\ \  \\ \  \       \ \  \  __\ \  \\ \  \_|/__\ \   __  \\ \_____  \\ \  \    \ \  \  \ \  \_|/__  
#  \ \  \    \ \  \    \ \  \           \ \  \  \ \  \\\  \\ \  \\ \  \\ \  \_|\ \\ \  \\ \  \       \ \  \|\__\_\  \\ \  \_|\ \\ \  \|\  \\|____|\  \\ \  \    \ \  \  \ \  \_|\ \ 
#   \ \__\    \ \__\    \ \__\           \ \__\  \ \_______\\ \__\\ \__\\ \_______\\ \__\\ \__\       \ \____________\\ \_______\\ \_______\ ____\_\  \\ \__\    \ \__\  \ \_______\
#    \|__|     \|__|     \|__|            \|__|   \|_______| \|__| \|__| \|_______| \|__| \|__|        \|____________| \|_______| \|_______||\_________\\|__|     \|__|   \|_______|
#                                                                                                                                           \|_________|                            
#
#                                                                       Ⓡ Developed by: @Mectoche Ⓡ
                                                                                                                                                                                   

app = Flask(__name__)
app.secret_key = '91ee8c748112b888b756598dsedbbe6dcd4b79f8c0a66d325aa' # your security key (flask)
TOKEN = r'C:\Users\Samuel\Desktop\MectocheToken\TOKEN\Debug\token.txt' #directory where the keys generated by Mectoche_token will be located within your server.

def read_token():
    if os.path.exists(TOKEN):
        with open(TOKEN, 'r') as file:
            return file.read().strip()
    return None

@app.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        token_input = request.form.get('token')
        if token_input == read_token():
            session['logged_in'] = True
            return redirect(url_for('protected'))
        else:
            return render_template('login.html', error='Token inválido.')
    return render_template('login.html')

@app.route('/protected')
def protected():
    if not session.get('logged_in'):
        abort(403)
    return render_template('protected.html')

@app.route('/logout')
def logout():
    session.pop('logged_in', None)
    return redirect(url_for('login'))

if __name__ == '__main__':
    app.run(debug=True)
